name: brasilposead_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  permission_handler: ^11.0.1
  file_picker: ^6.1.1
  webview_flutter_android: ^3.12.1
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  